vehicule:
    path:     /
    defaults: { _controller: "MyAppBackofficeBundle:Vehicule:index" }

vehicule_show:
    path:     /{id}/show
    defaults: { _controller: "MyAppBackofficeBundle:Vehicule:show" }

vehicule_new:
    path:     /new
    defaults: { _controller: "MyAppBackofficeBundle:Vehicule:new" }

vehicule_create:
    path:     /create
    defaults: { _controller: "MyAppBackofficeBundle:Vehicule:create" }
    requirements: { _method: post }

vehicule_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyAppBackofficeBundle:Vehicule:edit" }

vehicule_update:
    path:     /{id}/update
    defaults: { _controller: "MyAppBackofficeBundle:Vehicule:update" }
    requirements: { _method: post|put }

vehicule_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyAppBackofficeBundle:Vehicule:delete" }
    requirements: { _method: post|delete }
